### ISSUE TITLE
RDS - stop

### ISSUE THREAD

**Issue by bdronneau** [Interencheres/cpmawscli#14]
```
python cpmawscli.py --aws_access_key_id XXXX --aws_secret_access_key YYYY  --tag Env pp --tag Stack foo Rds stop
2016-09-30 15:00:56 NOTICE Connecting to region eu-west-1...
2016-09-30 15:00:57 NOTICE Connected to region eu-west-1
2016-09-30 15:00:57 NOTICE Listing RDS instances...
2016-09-30 15:01:24 NOTICE Filtering instances...
2016-09-30 15:01:24 NOTICE Creating snapshots...
2016-09-30 15:01:24 NOTICE Creating snapshot autoff-tf-20160930123344127393331wdk-2016-09-30-15-01-24...
Traceback (most recent call last):
  File "cpmawscli.py", line 5, in <module>
    orchestrator.run()
  File "/Users/bast/repos/interencheres/cpmawscli/CpmAWS/Orchestrator.py", line 74, in run
    ok = getattr(instance, self.parameters.action)()
  File "/Users/bast/repos/interencheres/cpmawscli/CpmAWS/plugins/Rds.py", line 42, in stop
    if instance.snapshot.create(instance):
  File "/Users/bast/repos/interencheres/cpmawscli/CpmAWS/classes/RdsSnapshot.py", line 22, in create
    for key, value in self.getTagFilter().iteritems():
  File "/Users/bast/repos/interencheres/cpmawscli/CpmAWS/classes/RdsSnapshot.py", line 108, in getTagFilter
    tags[tag[0]] = tag[1]
KeyError: 1
```

**Comment by fpietka** [comment]
Je n'avais pas vu que les tags étaient parcourus une seconde fois dans le cas de RDS. Vu que la forme à changé, ce code ne risque pas de fonctionner.
